### PR TITLE
feat(openapi): convert multiple and nullable types to OpenAPI

### PR DESCRIPTION
**Pull request by L2jLiga**

### CODE REVIEW

**Comment by SkeLLLa** [comment]
Does fastify by itself support such things?

**Comment by L2jLiga** [comment]
Sure, you can find it here: https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#validation

**Comment by SkeLLLa** [comment]
Good. As far as I rememberer `oneOf` sometimes doesn't work. But for now it's ok. If you have some problems with it, then make a PR replacing it with `anyOf`.

**Comment by L2jLiga** [comment]
Sure, thank you!

**Pull request merged**
